### ISSUE TITLE
ブラウザ上部にソースが表示される。

### ISSUE THREAD

**Issue by devdrops-com** [tinybeans/mt-plugin-MTAppjQuery#3]
カスタムフィールドを使用している場合、カスタムフィールドの値にhtmlタグやmtタグを含む情報を保存すると、ブラウザ上部にJavaScriptsの変数がうまく処理できずソースが表示されます。

おそらく、v1.10.1でmtappVars 変数にカスタムフィールドを対応したためと思います。
よろしければ、タグをエスケープして頂けたらありがたいです。

**Comment by tinybeans** [comment]
ありがとうございます。確認いたします。

**Comment by devdrops-com** [comment]
わかりました。「</script>」のタグが悪さしていたみたいです。
てっきりタグのエスケープが原因かと思っていました。
すみません！

とりあえず、「</script>」を「「\</script\>」」みたいにカスタムフィールドに登録しました。
これでいいのかわかりませんが・・・chromeはうまく処理できています。

**Comment by tinybeans** [comment]
ご連絡ありがとうございます。
エスケープにも問題があるようですので修正します。

**Comment by tinybeans** [comment]
修正したバージョン `v1.10.6` をリリースしました。
ご確認いただければ幸いです。
https://github.com/tinybeans/mt-plugin-MTAppjQuery/releases/tag/v1.10.6

**Comment by devdrops-com** [comment]
ありがとうございます！！！

**Comment by tinybeans** [comment]
ご指摘ありがとうございました。
このissueを閉じさせていただきます。
