### ISSUE TITLE
ドキュメント：Google Chrome 66 でセキュリティ警告が出る

### ISSUE THREAD

**Issue by rinopo** [tinybeans/mt-plugin-MTAppjQuery#6]
ドキュメントのサイトに Google Chrome 66 でアクセスすると、以下のようになります 😅 
https://document.bit-part.net/

<img width="1392" alt="-180420" src="https://user-images.githubusercontent.com/45791/39042687-6270e6d8-44c6-11e8-964c-45eefec98496.png">

下記に該当しているのではと思います：
[Google Developers Japan: Chrome が Symantec の証明書に対する信頼を破棄する予定について](https://developers-jp.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html)

**Comment by tinybeans** [comment]
大変失礼いたしました。
またご指摘ありがとうございました！
証明書を更新いたしましたのでご確認いただければ幸いです。

**Comment by rinopo** [comment]
👍
